Administrator.create!(account: 'zhanglejia', password: '123456', password_confirmation: '123456', name: '张乐佳')
Continent.create!([
  { name: '亚洲' },
  { name: '欧洲' },
  { name: '美洲' },
  { name: '非洲' },
  { name: '大洋洲' }
])
Country.create_with_levels!([
  { name: '阿尔巴尼亚', continent: Continent.where(name: '欧洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '阿尔及利亚', continent: Continent.where(name: '非洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '阿富汗', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 4 },
  { name: '埃尔比勒', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 4 },
  { name: '埃及', continent: Continent.where(name: '非洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '埃塞俄比亚', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '安哥拉', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '安提瓜和巴布达', continent: Continent.where(name: '美洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '敖德萨', continent: Continent.where(name: '欧洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '奥什', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '巴布亚新几内亚', continent: Continent.where(name: '大洋洲 ').first, p1: 1, p2: 0, p3: 3 },
  { name: '巴基斯坦', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '巴兰基亚', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '巴勒斯坦', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 2 },
  { name: '巴拿马', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 0 },
  { name: '巴塔', continent: Continent.where(name: '非洲').first, p1: 1, p2: 0, p3: 3 },
  { name: '巴新', continent: Continent.where(name: '大洋洲 ').first, p1: 3, p2: 2, p3: 0 },
  { name: '白俄罗斯', continent: Continent.where(name: '欧洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '贝宁', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '波黑', continent: Continent.where(name: '欧洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '波兰', continent: Continent.where(name: '欧洲').first, p1: 2, p2: 1, p3: 0 },
  { name: '玻利维亚', continent: Continent.where(name: '美洲').first, p1: 6, p2: 5, p3: 6 },
  { name: '博茨瓦纳', continent: Continent.where(name: '非洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '布基纳法索', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 0 },
  { name: '布隆迪', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '朝鲜', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '赤道几内亚', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 3 },
  { name: '登巴萨', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '东帝汶', continent: Continent.where(name: '亚洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '东盟使团', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '杜阿拉', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '多哥', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '多米尼加', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '多米尼克', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '厄瓜多尔', continent: Continent.where(name: '美洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '厄立特里亚', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 3 },
  { name: '非盟使团', continent: Continent.where(name: '非洲').first, p1: 0, p2: 0, p3: 3 },
  { name: '斐济', continent: Continent.where(name: '大洋洲 ').first, p1: 2, p2: 1, p3: 1 },
  { name: '佛得角', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '冈比亚', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '刚果（布）', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '刚果（金）', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 4 },
  { name: '哥伦比亚', continent: Continent.where(name: '美洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '哥斯达黎加', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '革但斯克', continent: Continent.where(name: '欧洲').first, p1: 0, p2: 1, p3: 0 },
  { name: '格林纳达', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '格鲁吉亚', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '古巴', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '瓜亚基尔', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '圭亚那', continent: Continent.where(name: '美洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '哈萨克斯坦', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '海地', continent: Continent.where(name: '美洲').first, p1: 3, p2: 2, p3: 4 },
  { name: '黑山', continent: Continent.where(name: '欧洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '胡志明', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '基里巴斯', continent: Continent.where(name: '大洋洲 ').first, p1: 4, p2: 3, p3: 0 },
  { name: '吉布提', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 4 },
  { name: '吉尔吉斯斯坦', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '几内亚', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 4 },
  { name: '几内亚比绍', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 5 },
  { name: '加尔各答', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '加纳', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '加蓬', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '柬埔寨', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '津巴布韦', continent: Continent.where(name: '非洲').first, p1: 2, p2: 1, p3: 2 },
  { name: '喀麦隆', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '卡拉奇', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 3 },
  { name: '科摩罗', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '科特迪瓦', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '肯尼亚', continent: Continent.where(name: '非洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '拉各斯', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '拉合尔', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '莱索托', continent: Continent.where(name: '非洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '琅勃拉邦', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '老挝', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '利比里亚', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 4 },
  { name: '卢旺达', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '马达加斯加', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '马尔代夫', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '马拉维', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 3 },
  { name: '马里', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 4 },
  { name: '马其顿', continent: Continent.where(name: '欧洲').first, p1: 2, p2: 1, p3: 2 },
  { name: '马绍尔', continent: Continent.where(name: '大洋洲 ').first, p1: 3, p2: 2, p3: 2 },
  { name: '曼德勒', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '毛里塔尼亚', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 4 },
  { name: '蒙古', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '孟加拉', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 4 },
  { name: '孟买', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '秘鲁', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '密克罗尼西亚', continent: Continent.where(name: '大洋洲 ').first, p1: 3, p2: 2, p3: 2 },
  { name: '棉兰', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '缅甸', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '莫桑比克', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '墨西哥', continent: Continent.where(name: '美洲').first, p1: 4, p2: 3, p3: 2 },
  { name: '纳米比亚', continent: Continent.where(name: '非洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '南苏丹', continent: Continent.where(name: '非洲').first, p1: 1, p2: 0, p3: 5 },
  { name: '瑙鲁', continent: Continent.where(name: '大洋洲 ').first, p1: 4, p2: 3, p3: 0 },
  { name: '内比都', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '尼泊尔', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 4 },
  { name: '尼日尔', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 5 },
  { name: '尼日利亚', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '帕皮提', continent: Continent.where(name: '大洋洲 ').first, p1: 2, p2: 1, p3: 0 },
  { name: '普里什蒂纳', continent: Continent.where(name: '欧洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '清津', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '萨摩亚', continent: Continent.where(name: '大洋洲 ').first, p1: 2, p2: 1, p3: 1 },
  { name: '塞尔维亚', continent: Continent.where(name: '欧洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '塞拉利昂', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 4 },
  { name: '塞内加尔', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '桑给巴尔', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '圣多美和普林西比', continent: Continent.where(name: '非洲').first, p1: 1, p2: 0, p3: 3 },
  { name: '圣卢西亚', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '圣普', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 0 },
  { name: '斯里兰卡', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '泗水', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '苏丹', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 4 },
  { name: '苏里南', continent: Continent.where(name: '美洲').first, p1: 2, p2: 1, p3: 2 },
  { name: '索马里', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 5 },
  { name: '塔吉克斯坦', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 2 },
  { name: '塔马塔夫', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 0 },
  { name: '坦桑尼亚', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '汤加', continent: Continent.where(name: '大洋洲 ').first, p1: 3, p2: 2, p3: 2 },
  { name: '土库曼斯坦', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 2 },
  { name: '瓦努阿图', continent: Continent.where(name: '大洋洲 ').first, p1: 3, p2: 2, p3: 2 },
  { name: '委内瑞拉', continent: Continent.where(name: '美洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '乌干达', continent: Continent.where(name: '非洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '乌克兰', continent: Continent.where(name: '欧洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '乌兹别克斯坦', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '叙利亚', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '亚丁', continent: Continent.where(name: '亚洲').first, p1: 4, p2: 3, p3: 3 },
  { name: '亚历山大', continent: Continent.where(name: '非洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '亚美尼亚', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '也门', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 3 },
  { name: '伊拉克', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 5 },
  { name: '伊朗', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 1 },
  { name: '印度', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '印度尼西亚', continent: Continent.where(name: '亚洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '越南', continent: Continent.where(name: '亚洲').first, p1: 3, p2: 2, p3: 2 },
  { name: '赞比亚', continent: Continent.where(name: '非洲').first, p1: 2, p2: 1, p3: 1 },
  { name: '扎门乌德', continent: Continent.where(name: '亚洲').first, p1: 1, p2: 0, p3: 2 },
  { name: '乍得', continent: Continent.where(name: '非洲').first, p1: 5, p2: 4, p3: 5 },
  { name: '中非', continent: Continent.where(name: '非洲').first, p1: 4, p2: 3, p3: 5 }
])
Currency.create!([
  { name: 'AED', description: 'United Arab Emirates Dirham (AED)' },
  { name: 'AFN', description: 'Afghan Afghani (AFN)' },
  { name: 'ALL', description: 'Albanian Lek (ALL)' },
  { name: 'AMD', description: 'Armenian Dram (AMD)' },
  { name: 'ANG', description: 'Netherlands Antillean Guilder (ANG)' },
  { name: 'AOA', description: 'Angolan Kwanza (AOA)' },
  { name: 'ARS', description: 'Argentine Peso (ARS)' },
  { name: 'AUD', description: 'Australian Dollar (A$)', important: true },
  { name: 'AWG', description: 'Aruban Florin (AWG)' },
  { name: 'AZN', description: 'Azerbaijani Manat (AZN)' },
  { name: 'BAM', description: 'Bosnia-Herzegovina Convertible Mark (BAM)' },
  { name: 'BBD', description: 'Barbadian Dollar (BBD)' },
  { name: 'BDT', description: 'Bangladeshi Taka (BDT)' },
  { name: 'BGN', description: 'Bulgarian Lev (BGN)' },
  { name: 'BHD', description: 'Bahraini Dinar (BHD)' },
  { name: 'BIF', description: 'Burundian Franc (BIF)' },
  { name: 'BMD', description: 'Bermudan Dollar (BMD)' },
  { name: 'BND', description: 'Brunei Dollar (BND)' },
  { name: 'BOB', description: 'Bolivian Boliviano (BOB)' },
  { name: 'BRL', description: 'Brazilian Real (R$)' },
  { name: 'BSD', description: 'Bahamian Dollar (BSD)' },
  { name: 'BTC', description: 'Bitcoin (฿)' },
  { name: 'BTN', description: 'Bhutanese Ngultrum (BTN)' },
  { name: 'BWP', description: 'Botswanan Pula (BWP)' },
  { name: 'BYN', description: 'Belarusian Ruble (BYN)' },
  { name: 'BYR', description: 'Belarusian Ruble (2000-2016) (BYR)' },
  { name: 'BZD', description: 'Belize Dollar (BZD)' },
  { name: 'CAD', description: 'Canadian Dollar (CA$)', important: true },
  { name: 'CDF', description: 'Congolese Franc (CDF)' },
  { name: 'CHF', description: 'Swiss Franc (CHF)' },
  { name: 'CLF', description: 'Chilean Unit of Account (UF) (CLF)' },
  { name: 'CLP', description: 'Chilean Peso (CLP)' },
  { name: 'CNH', description: 'CNH (CNH)' },
  { name: 'CNY', description: 'Chinese Yuan (CN¥)', important: true },
  { name: 'COP', description: 'Colombian Peso (COP)' },
  { name: 'CRC', description: 'Costa Rican Colón (CRC)' },
  { name: 'CUP', description: 'Cuban Peso (CUP)' },
  { name: 'CVE', description: 'Cape Verdean Escudo (CVE)' },
  { name: 'CZK', description: 'Czech Republic Koruna (CZK)' },
  { name: 'DEM', description: 'German Mark (DEM)' },
  { name: 'DJF', description: 'Djiboutian Franc (DJF)' },
  { name: 'DKK', description: 'Danish Krone (DKK)' },
  { name: 'DOP', description: 'Dominican Peso (DOP)' },
  { name: 'DZD', description: 'Algerian Dinar (DZD)' },
  { name: 'EGP', description: 'Egyptian Pound (EGP)' },
  { name: 'ERN', description: 'Eritrean Nakfa (ERN)' },
  { name: 'ETB', description: 'Ethiopian Birr (ETB)' },
  { name: 'EUR', description: 'Euro (€)', important: true },
  { name: 'FIM', description: 'Finnish Markka (FIM)' },
  { name: 'FJD', description: 'Fijian Dollar (FJD)' },
  { name: 'FKP', description: 'Falkland Islands Pound (FKP)' },
  { name: 'FRF', description: 'French Franc (FRF)', important: true },
  { name: 'GBP', description: 'British Pound (£)', important: true },
  { name: 'GEL', description: 'Georgian Lari (GEL)' },
  { name: 'GHS', description: 'Ghanaian Cedi (GHS)' },
  { name: 'GIP', description: 'Gibraltar Pound (GIP)' },
  { name: 'GMD', description: 'Gambian Dalasi (GMD)' },
  { name: 'GNF', description: 'Guinean Franc (GNF)' },
  { name: 'GTQ', description: 'Guatemalan Quetzal (GTQ)' },
  { name: 'GYD', description: 'Guyanaese Dollar (GYD)' },
  { name: 'HKD', description: 'Hong Kong Dollar (HK$)' },
  { name: 'HNL', description: 'Honduran Lempira (HNL)' },
  { name: 'HRK', description: 'Croatian Kuna (HRK)' },
  { name: 'HTG', description: 'Haitian Gourde (HTG)' },
  { name: 'HUF', description: 'Hungarian Forint (HUF)' },
  { name: 'IDR', description: 'Indonesian Rupiah (IDR)' },
  { name: 'IEP', description: 'Irish Pound (IEP)' },
  { name: 'ILS', description: 'Israeli New Sheqel (₪)' },
  { name: 'INR', description: 'Indian Rupee (₹)' },
  { name: 'IQD', description: 'Iraqi Dinar (IQD)' },
  { name: 'IRR', description: 'Iranian Rial (IRR)' },
  { name: 'ISK', description: 'Icelandic Króna (ISK)' },
  { name: 'ITL', description: 'Italian Lira (ITL)', important: true },
  { name: 'JMD', description: 'Jamaican Dollar (JMD)' },
  { name: 'JOD', description: 'Jordanian Dinar (JOD)' },
  { name: 'JPY', description: 'Japanese Yen (¥)', important: true },
  { name: 'KES', description: 'Kenyan Shilling (KES)' },
  { name: 'KGS', description: 'Kyrgystani Som (KGS)' },
  { name: 'KHR', description: 'Cambodian Riel (KHR)' },
  { name: 'KMF', description: 'Comorian Franc (KMF)' },
  { name: 'KPW', description: 'North Korean Won (KPW)' },
  { name: 'KRW', description: 'South Korean Won (₩)' },
  { name: 'KWD', description: 'Kuwaiti Dinar (KWD)' },
  { name: 'KYD', description: 'Cayman Islands Dollar (KYD)' },
  { name: 'KZT', description: 'Kazakhstani Tenge (KZT)' },
  { name: 'LAK', description: 'Laotian Kip (LAK)' },
  { name: 'LBP', description: 'Lebanese Pound (LBP)' },
  { name: 'LKR', description: 'Sri Lankan Rupee (LKR)' },
  { name: 'LRD', description: 'Liberian Dollar (LRD)' },
  { name: 'LSL', description: 'Lesotho Loti (LSL)' },
  { name: 'LTL', description: 'Lithuanian Litas (LTL)' },
  { name: 'LVL', description: 'Latvian Lats (LVL)' },
  { name: 'LYD', description: 'Libyan Dinar (LYD)' },
  { name: 'MAD', description: 'Moroccan Dirham (MAD)' },
  { name: 'MDL', description: 'Moldovan Leu (MDL)' },
  { name: 'MGA', description: 'Malagasy Ariary (MGA)' },
  { name: 'MKD', description: 'Macedonian Denar (MKD)' },
  { name: 'MMK', description: 'Myanmar Kyat (MMK)' },
  { name: 'MNT', description: 'Mongolian Tugrik (MNT)' },
  { name: 'MOP', description: 'Macanese Pataca (MOP)' },
  { name: 'MRO', description: 'Mauritanian Ouguiya (MRO)' },
  { name: 'MUR', description: 'Mauritian Rupee (MUR)' },
  { name: 'MVR', description: 'Maldivian Rufiyaa (MVR)' },
  { name: 'MWK', description: 'Malawian Kwacha (MWK)' },
  { name: 'MXN', description: 'Mexican Peso (MX$)' },
  { name: 'MYR', description: 'Malaysian Ringgit (MYR)', important: true },
  { name: 'MZN', description: 'Mozambican Metical (MZN)' },
  { name: 'NAD', description: 'Namibian Dollar (NAD)' },
  { name: 'NGN', description: 'Nigerian Naira (NGN)' },
  { name: 'NIO', description: 'Nicaraguan Córdoba (NIO)' },
  { name: 'NOK', description: 'Norwegian Krone (NOK)' },
  { name: 'NPR', description: 'Nepalese Rupee (NPR)' },
  { name: 'NZD', description: 'New Zealand Dollar (NZ$)', important: true },
  { name: 'OMR', description: 'Omani Rial (OMR)' },
  { name: 'PAB', description: 'Panamanian Balboa (PAB)' },
  { name: 'PEN', description: 'Peruvian Nuevo Sol (PEN)' },
  { name: 'PGK', description: 'Papua New Guinean Kina (PGK)' },
  { name: 'PHP', description: 'Philippine Peso (PHP)' },
  { name: 'PKG', description: 'PKG (PKG)' },
  { name: 'PKR', description: 'Pakistani Rupee (PKR)' },
  { name: 'PLN', description: 'Polish Zloty (PLN)' },
  { name: 'PYG', description: 'Paraguayan Guarani (PYG)' },
  { name: 'QAR', description: 'Qatari Rial (QAR)' },
  { name: 'RON', description: 'Romanian Leu (RON)' },
  { name: 'RSD', description: 'Serbian Dinar (RSD)' },
  { name: 'RUB', description: 'Russian Ruble (RUB)', important: true },
  { name: 'RWF', description: 'Rwandan Franc (RWF)' },
  { name: 'SAR', description: 'Saudi Riyal (SAR)' },
  { name: 'SBD', description: 'Solomon Islands Dollar (SBD)' },
  { name: 'SCR', description: 'Seychellois Rupee (SCR)' },
  { name: 'SDG', description: 'Sudanese Pound (SDG)' },
  { name: 'SEK', description: 'Swedish Krona (SEK)' },
  { name: 'SGD', description: 'Singapore Dollar (SGD)' },
  { name: 'SHP', description: 'St. Helena Pound (SHP)' },
  { name: 'SKK', description: 'Slovak Koruna (SKK)' },
  { name: 'SLL', description: 'Sierra Leonean Leone (SLL)' },
  { name: 'SOS', description: 'Somali Shilling (SOS)' },
  { name: 'SRD', description: 'Surinamese Dollar (SRD)' },
  { name: 'STD', description: 'São Tomé & Príncipe Dobra (STD)' },
  { name: 'SVC', description: 'Salvadoran Colón (SVC)' },
  { name: 'SYP', description: 'Syrian Pound (SYP)' },
  { name: 'SZL', description: 'Swazi Lilangeni (SZL)' },
  { name: 'THB', description: 'Thai Baht (THB)', important: true },
  { name: 'TJS', description: 'Tajikistani Somoni (TJS)' },
  { name: 'TMT', description: 'Turkmenistani Manat (TMT)' },
  { name: 'TND', description: 'Tunisian Dinar (TND)' },
  { name: 'TOP', description: 'Tongan Paʻanga (TOP)' },
  { name: 'TRY', description: 'Turkish Lira (TRY)' },
  { name: 'TTD', description: 'Trinidad & Tobago Dollar (TTD)' },
  { name: 'TWD', description: 'New Taiwan Dollar (NT$)' },
  { name: 'TZS', description: 'Tanzanian Shilling (TZS)' },
  { name: 'UAH', description: 'Ukrainian Hryvnia (UAH)' },
  { name: 'UGX', description: 'Ugandan Shilling (UGX)' },
  { name: 'USD', description: 'US Dollar ($)', important: true },
  { name: 'UYU', description: 'Uruguayan Peso (UYU)' },
  { name: 'UZS', description: 'Uzbekistani Som (UZS)' },
  { name: 'VEF', description: 'Venezuelan Bolívar (VEF)' },
  { name: 'VND', description: 'Vietnamese Dong (₫)' },
  { name: 'VUV', description: 'Vanuatu Vatu (VUV)' },
  { name: 'WST', description: 'Samoan Tala (WST)' },
  { name: 'XAF', description: 'Central African CFA Franc (FCFA)' },
  { name: 'XCD', description: 'East Caribbean Dollar (EC$)' },
  { name: 'XDR', description: 'Special Drawing Rights (XDR)' },
  { name: 'XOF', description: 'West African CFA Franc (CFA)' },
  { name: 'XPF', description: 'CFP Franc (CFPF)' },
  { name: 'YER', description: 'Yemeni Rial (YER)' },
  { name: 'ZAR', description: 'South African Rand (ZAR)' },
  { name: 'ZMK', description: 'Zambian Kwacha (1968–2012) (ZMK)' },
  { name: 'ZMW', description: 'Zambian Kwacha (ZMW)' },
  { name: 'ZWL', description: 'Zimbabwean Dollar (2009) (ZWL)' }
])
SalaryPolicy.create!([
  { type: :assistant, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 8400 },
  { type: :instructor, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 8800 },
  { type: :associate_professor, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 9600 },
  { type: :professor, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 10400 },
  { type: :assistant, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 9750 },
  { type: :instructor, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 11050 },
  { type: :associate_professor, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 12350 },
  { type: :professor, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 13650 },
  { type: :assistant, started_at: '2014-01-01', ended_at: '2020-12-31', amount: 12000 },
  { type: :instructor, started_at: '2014-01-01', ended_at: '2020-12-31', amount: 13600 },
  { type: :associate_professor, started_at: '2014-01-01', ended_at: '2020-12-31', amount: 15200 },
  { type: :professor, started_at: '2014-01-01', ended_at: '2020-12-31', amount: 16800 }
])
SpouseSubsidyPolicy.create!([
  { type: :unmarried, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 0 },
  { type: :not_accompanied, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 1300 },
  { type: :accompanied, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 3250 },
  { type: :unmarried, started_at: '2014-01-01', ended_at: '2020-12-31', amount: 0 },
  { type: :not_accompanied, started_at: '2014-01-01', ended_at: '2020-12-31', amount: 1600 },
  { type: :accompanied, started_at: '2014-01-01', ended_at: '2020-12-31', amount: 4000 }
])
TravelSubsidyPolicy.create!([
  { level: 1, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 1600 },
  { level: 0, started_at: '2011-07-01', ended_at: '2020-12-31', amount: 2600 },
  { level: 2, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 1600 },
  { level: 1, started_at: '2011-07-01', ended_at: '2020-12-31', amount: 2600 },
  { level: 3, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 3200 },
  { level: 2, started_at: '2011-07-01', ended_at: '2020-12-31', amount: 3900 },
  { level: 4, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 3200 },
  { level: 3, started_at: '2011-07-01', ended_at: '2020-12-31', amount: 3900 },
  { level: 5, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 3200 },
  { level: 4, started_at: '2011-07-01', ended_at: '2020-12-31', amount: 3900 },
  { level: 6, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 3200 },
  { level: 5, started_at: '2011-07-01', ended_at: '2020-12-31', amount: 3900 },
  { level: 6, started_at: '2016-01-01', ended_at: '2020-12-31', amount: 3900 }
])
CountrySubsidyPolicy.create!([
  { level: 2, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 1600 },
  { level: 1, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 1170 },
  { level: 1, started_at: '2014-01-01', ended_at: '2015-12-31', amount: 1440 },
  { level: 1, started_at: '2016-01-01', ended_at: '2020-12-31', amount: 3100 },
  { level: 3, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 3200 },
  { level: 2, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 3250 },
  { level: 2, started_at: '2014-01-01', ended_at: '2015-12-31', amount: 4000 },
  { level: 2, started_at: '2016-01-01', ended_at: '2020-12-31', amount: 6500 },
  { level: 4, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 4800 },
  { level: 3, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 5330 },
  { level: 3, started_at: '2014-01-01', ended_at: '2015-12-31', amount: 6560 },
  { level: 3, started_at: '2016-01-01', ended_at: '2020-12-31', amount: 9900 },
  { level: 5, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 6400 },
  { level: 4, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 7475 },
  { level: 4, started_at: '2014-01-01', ended_at: '2015-12-31', amount: 9200 },
  { level: 4, started_at: '2016-01-01', ended_at: '2020-12-31', amount: 13400 },
  { level: 6, started_at: '2000-01-01', ended_at: '2011-06-30', amount: 8000 },
  { level: 5, started_at: '2011-07-01', ended_at: '2013-12-31', amount: 9750 },
  { level: 5, started_at: '2014-01-01', ended_at: '2015-12-31', amount: 12000 },
  { level: 5, started_at: '2016-01-01', ended_at: '2020-12-31', amount: 17000 },
  { level: 6, started_at: '2016-01-01', ended_at: '2020-12-31', amount: 20700 }
])
